_wandb:
    value:
        cli_version: 0.23.1
        e:
            ajm91iws57wq4axu4jdgibze2ulr8d7s:
                args:
                    - --tag
                    - linear_aircraft_knn
                    - --dataset
                    - aircraft
                    - --model
                    - resnet50
                    - --data_folder
                    - ./data
                    - --pretrained
                    - --pretrained_ckpt
                    - save/aircraft_resnet50_pretrain_simclr_baseline_aircraft/last.pth
                    - --method
                    - simclr
                    - --knn
                    - --topk
                    - "20"
                    - "200"
                codePath: train_sup.py
                codePathLocal: train_sup.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "502392610816"
                        used: "457026015232"
                email: tinbgbg05@gmail.com
                executable: /mnt/disk1/miniconda3/envs/tindl/bin/python
                git:
                    commit: 97b4c9e6492a24d833d6391f203dad1793a08aa6
                    remote: https://github.com/sungnyun/openssl-simcore
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-131c9a56-60f2-3bb0-7b04-575a2e52bd15
                host: vaipe-Z790-UD-AX
                memory:
                    total: "67163844608"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /mnt/disk3/tinvt/openssl-simcore/train_sup.py
                python: CPython 3.10.12
                root: /mnt/disk3/tinvt/openssl-simcore
                startedAt: "2026-03-27T19:21:55.372186Z"
                writerId: ajm91iws57wq4axu4jdgibze2ulr8d7s
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
                - 105
            "2":
                - 1
                - 41
                - 49
                - 63
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 256
cosine:
    value: false
data_folder:
    value: ./data
dataset:
    value: aircraft
e2e:
    value: false
epochs:
    value: 100
from_sl_official:
    value: false
from_ssl_official:
    value: false
img_size:
    value: 224
knn:
    value: true
label_ratio:
    value: 1
learning_rate:
    value: 0.1
lr_decay_epochs:
    value:
        - 60
        - 80
lr_decay_rate:
    value: 0.1
method:
    value: simclr
model:
    value: resnet50
model_name:
    value: aircraft_resnet50_le_from_simclr_linear_aircraft_knn
momentum:
    value: 0.9
multi_attribute:
    value: ""
n_cls:
    value: 100
num_workers:
    value: 16
optimizer:
    value: sgd
pretrained:
    value: true
pretrained_ckpt:
    value: save/aircraft_resnet50_pretrain_simclr_baseline_aircraft/last.pth
print_freq:
    value: 10
save_dir:
    value: ./save
save_folder:
    value: ./save/aircraft_resnet50_le_from_simclr_linear_aircraft_knn
save_freq:
    value: 1000
seed:
    value: 0
semi:
    value: false
tag:
    value: linear_aircraft_knn
topk:
    value:
        - 20
        - 200
wandb_project:
    value: openssl-simcore
warm:
    value: false
warm_epochs:
    value: 0
wd_scheduler:
    value: false
weight_decay:
    value: 0.0001
