_wandb:
    value:
        cli_version: 0.23.1
        e:
            3k0kc3lcd4n85f2tf77e437j6xid6c3l:
                args:
                    - --tag
                    - TEST_baseline
                    - --model
                    - resnet50
                    - --batch_size
                    - "128"
                    - --precision
                    - --dataset1
                    - aircraft
                    - --data_folder1
                    - ./data/aircraft
                    - --method
                    - simclr
                    - --epochs
                    - "2"
                    - --cosine
                    - --optimizer
                    - sgd
                    - --learning_rate
                    - "0.5"
                    - --weight_decay
                    - "1e-4"
                    - --no_sampling
                    - --num_workers
                    - "16"
                codePath: train_selfsup.py
                codePathLocal: train_selfsup.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "502392610816"
                        used: "305632993280"
                email: tinbgbg05@gmail.com
                executable: /mnt/disk1/miniconda3/envs/tindl/bin/python
                git:
                    commit: 97b4c9e6492a24d833d6391f203dad1793a08aa6
                    remote: https://github.com/sungnyun/openssl-simcore
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-131c9a56-60f2-3bb0-7b04-575a2e52bd15
                host: vaipe-Z790-UD-AX
                memory:
                    total: "67163308032"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /mnt/disk3/tinvt/openssl-simcore/train_selfsup.py
                python: CPython 3.10.12
                root: /mnt/disk3/tinvt/openssl-simcore
                startedAt: "2026-04-08T06:07:03.317301Z"
                writerId: 3k0kc3lcd4n85f2tf77e437j6xid6c3l
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 105
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 105
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 128
clip_grad:
    value: 0
cluster_num:
    value: 100
cosine:
    value: true
data_folder:
    value: ./data/
data_folder1:
    value: ./data/aircraft
data_folder2:
    value: null
dataset:
    value: cars
dataset1:
    value: aircraft
dataset2:
    value: null
ema_scheduler:
    value: true
epochs:
    value: 2
freeze_last_layer:
    value: 0
freeze_prototypes:
    value: 1
from_ssl_official:
    value: false
img_size:
    value: 224
initial_ema:
    value: 0.996
initial_temp:
    value: 0.04
learning_rate:
    value: 0.5
local_crops_number:
    value: 0
lr_decay_epochs:
    value:
        - 200
        - 300
lr_decay_rate:
    value: 0.1
mask_ratio:
    value: 0.75
merge_dataset:
    value: false
method:
    value: simclr
model:
    value: resnet50
model_name:
    value: cars_resnet50_pretrain_simclr_TEST_baseline
momentum:
    value: 0.9
n_cls:
    value: 196
no_sampling:
    value: true
norm_pix_loss:
    value: false
num_workers:
    value: 16
optimizer:
    value: sgd
patience:
    value: 20
precision:
    value: true
print_freq:
    value: 10
prototypes:
    value: 100
resume:
    value: null
retrieval_ckpt:
    value: null
sampling_method:
    value: simcore
sampling_ratio:
    value: 0
sampling_times:
    value: 1
save_dir:
    value: ./save
save_folder:
    value: ./save/cars_resnet50_pretrain_simclr_TEST_baseline
save_freq:
    value: 1000
seed:
    value: 0
stop:
    value: false
stop_thresh:
    value: 0.95
tag:
    value: TEST_baseline
temp_warmup_epochs:
    value: 0
warm:
    value: false
warm_epochs:
    value: 0
wd_scheduler:
    value: false
weight_decay:
    value: 0.0001
weight_decay_end:
    value: 0
